<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework> <!-- or your desired framework -->
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems> <!-- Disable implicit compile items -->
    <RuntimeIdentifiers>win-x64;linux-x64;osx-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <!-- Define symbols for Windows -->
  <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'win-x64'">
    <DefineConstants>WINDOWS</DefineConstants>
  </PropertyGroup>

  <!-- Define symbols for Linux -->
  <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'linux-x64'">
    <DefineConstants>LINUX</DefineConstants>
  </PropertyGroup>

  <!-- Define symbols for macOS -->
  <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'osx-x64'">
    <DefineConstants>OSX</DefineConstants>
  </PropertyGroup>

  <ItemGroup>    
    <Compile Include="Wrappers\Ipc.cs" />
    <Compile Include="Wrappers\Worklet.cs" />
  </ItemGroup>

</Project>
