<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>BareKit</PackageId>
    <Version>1.0.0</Version>
    <Authors>YourName</Authors>
    <Description>My cross-platform BareKit .NET wrapper</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\prebuilds\dotnet\runtime\win-x64\native\bare-kit.dll"
          Pack="true"
          PackagePath="runtimes/win-x64/native/bare-kit.dll" />
    
    <None Include="..\..\..\prebuilds\dotnet\runtime\linux-x64\native\libbare-kit.so"
          Pack="true"
          PackagePath="runtimes/linux-x64/native/libbare-kit.so" />
          
    <None Include="..\..\..\prebuilds\dotnet\runtime\osx-x64\native\libbare-kit.dylib"
          Pack="true"
          PackagePath="runtimes/osx-x64/native/libbare-kit.dylib" />
  </ItemGroup>
</Project>
